sudo: required
dist: trusty
language: c
cache: apt

branches:
  only:
    - 'master'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install cmake

script:
  - mkdir build && cd build && cmake ../ && make
